<!DOCTYPE html>
<html lang="en">
	<head>
		<!-- Meta -->
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
	    <meta name="description" content="">
	    <meta name="author" content="">
	    
	    <!-- Favicon -->
	    <!-- HTML and images generated by http://realfavicongenerator.net/ -->
	    <link rel="shortcut icon" href="/img/favicons/favicon.ico">
		<link rel="apple-touch-icon" sizes="57x57" href="/img/favicons/apple-touch-icon-57x57.png">
		<link rel="apple-touch-icon" sizes="114x114" href="/img/favicons/apple-touch-icon-114x114.png">
		<link rel="apple-touch-icon" sizes="72x72" href="/img/favicons/apple-touch-icon-72x72.png">
		<link rel="apple-touch-icon" sizes="144x144" href="/img/favicons/apple-touch-icon-144x144.png">
		<link rel="apple-touch-icon" sizes="60x60" href="/img/favicons/apple-touch-icon-60x60.png">
		<link rel="apple-touch-icon" sizes="120x120" href="/img/favicons/apple-touch-icon-120x120.png">
		<link rel="apple-touch-icon" sizes="76x76" href="/img/favicons/apple-touch-icon-76x76.png">
		<link rel="apple-touch-icon" sizes="152x152" href="/img/favicons/apple-touch-icon-152x152.png">
		<link rel="apple-touch-icon" sizes="180x180" href="/img/favicons/apple-touch-icon-180x180.png">
		<meta name="apple-mobile-web-app-title" content="U of T iGEM 2014 ">
		<link rel="icon" type="image/png" href="/img/favicons/favicon-192x192.png" sizes="192x192">
		<link rel="icon" type="image/png" href="/img/favicons/favicon-160x160.png" sizes="160x160">
		<link rel="icon" type="image/png" href="/img/favicons/favicon-96x96.png" sizes="96x96">
		<link rel="icon" type="image/png" href="/img/favicons/favicon-16x16.png" sizes="16x16">
		<link rel="icon" type="image/png" href="/img/favicons/favicon-32x32.png" sizes="32x32">
		<meta name="msapplication-TileColor" content="#00aba9">
		<meta name="msapplication-TileImage" content="/img/favicons/mstile-144x144.png">
		<meta name="msapplication-config" content="/img/favicons/browserconfig.xml">
		<meta name="application-name" content="U of T iGEM 2014 ">

		<!-- Title -->
		<title>Team:Toronto - 2014.igem.org</title>
		
		<!-- Bootstrap -->
		<!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
		<!-- Optional theme -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
		
		<!-- Main styles -->
		<!-- See scss/style.scss for styles prior to compiling -->
		<link rel="stylesheet" href="css/style.css">
		
		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
	    <!--[if lt IE 9]>
	      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	    <![endif]-->
	</head>
	<body>
		
	
